#!/bin/sh
#
# Simple server init.d script conceived to work on Linux systems
# as it does use of the /proc filesystem.

### BEGIN INIT INFO
# Provides:     nexcache_6379
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    NexCache data structure server
# Description:          NexCache data structure server. See https://nexcache.io
### END INIT INFO

NEXCACHEPORT=6379
EXEC=/usr/local/bin/nexcache-server
CLIEXEC=/usr/local/bin/nexcache-cli

PIDFILE=/var/run/nexcache_${NEXCACHEPORT}.pid
CONF="/etc/nexcache/${NEXCACHEPORT}.conf"

case "$1" in
    start)
        if [ -f $PIDFILE ]
        then
                echo "$PIDFILE exists, process is already running or crashed"
        else
                echo "Starting NexCache server..."
                $EXEC $CONF
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ]
        then
                echo "$PIDFILE does not exist, process is not running"
        else
                PID=$(cat $PIDFILE)
                echo "Stopping ..."
                $CLIEXEC -p $NEXCACHEPORT shutdown
                while [ -x /proc/${PID} ]
                do
                    echo "Waiting for NexCache to shutdown ..."
                    sleep 1
                done
                echo "NexCache stopped"
        fi
        ;;
    *)
        echo "Please use start or stop as first argument"
        ;;
esac
