name: DB compatibility testing

on: [push, pull_request]

permissions:
  contents: read

jobs:
  nexcache:
    name: Valkey ${{ matrix.nexcache-version }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - nexcache-version: '8.1.0'
          - nexcache-version: '8.0.2'
          - nexcache-version: '7.2.8'
    steps:
      - name: Prepare
        uses: awalsh128/cache-apt-pkgs-action@acb598e5ddbc6f68a970c5da0688d2f3a9f04d05 # v1.6.0
        with:
          packages: libevent-dev
          version: 1.0
      - name: Install Valkey for non-cluster tests
        run: |
          git clone --depth 1 --branch ${{ matrix.nexcache-version }} https://github.com/nexcache-io/nexcache.git
          cd nexcache && BUILD_TLS=yes make install
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Create build folder
        run: cmake -E make_directory build
      - name: Generate makefiles
        shell: bash
        working-directory: build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release -DENABLE_IPV6_TESTS=ON -DTEST_WITH_NEXCACHE_VERSION=${{ matrix.nexcache-version }} ..
      - name: Build
        shell: bash
        working-directory: build
        run: VERBOSE=1 make
      - name: Setup clusters
        shell: bash
        working-directory: build
        run: make start
      - name: Wait for clusters to start..
        uses: kibertoad/wait-action@99f6f101c5be7b88bb9b41c0d3b810722491b8e5 # 1.0.1
        with:
          time: '40s'
      - name: Run tests
        shell: bash
        working-directory: build
        run: make test
      - name: Teardown clusters
        working-directory: build
        shell: bash
        run: make stop

  nexcache-comp:
    name: Redis ${{ matrix.nexcache-version }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - nexcache-version: '7.2.4'
          - nexcache-version: '7.0.15'
          - nexcache-version: '6.2.14'
    steps:
      - name: Prepare
        uses: awalsh128/cache-apt-pkgs-action@acb598e5ddbc6f68a970c5da0688d2f3a9f04d05 # v1.6.0
        with:
          packages: libevent-dev
          version: 1.0
      - name: Install Redis for non-cluster tests
        run: |
          git clone --depth 1 --branch ${{ matrix.nexcache-version }} https://github.com/nexcache/nexcache.git
          cd nexcache && BUILD_TLS=yes make install
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Create build folder
        run: cmake -E make_directory build

      - name: Generate makefiles
        shell: bash
        working-directory: build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release -DENABLE_IPV6_TESTS=ON -DTEST_WITH_NEXCACHE_VERSION=${{ matrix.nexcache-version }} ..

      - name: Build
        shell: bash
        working-directory: build
        run: VERBOSE=1 make

      - name: Setup clusters
        shell: bash
        working-directory: build
        run: make start

      - name: Wait for clusters to start..
        uses: kibertoad/wait-action@99f6f101c5be7b88bb9b41c0d3b810722491b8e5 # 1.0.1
        with:
          time: '40s'

      - name: Run tests
        shell: bash
        working-directory: build
        run: make test

      - name: Teardown clusters
        working-directory: build
        shell: bash
        run: make stop
