acl.o: acl.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
  connection.h ae.h monotonic.h commands.h allocator_defrag.h dict.h \
  mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h version.h \
  util.h latency.h trace/trace.h trace/trace_aof.h trace/trace_cluster.h \
  trace/trace_server.h trace/trace_db.h trace/trace_rdb.h \
  trace/trace_commands.h sparkline.h quicklist.h expire.h rax.h \
  memory_prefetch.h vset.h entry.h lrulfu.h valkeymodule.h zipmap.h \
  ziplist.h sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h \
  sha256.h module.h intset.h script.h scripting_engine.h
adlist.o: adlist.c adlist.h serverassert.h zmalloc.h
ae.o: ae.c ae.h monotonic.h fmacros.h anet.h serverassert.h zmalloc.h \
  config.h ae_kqueue.c
allocator_defrag.o: allocator_defrag.c server.h fmacros.h config.h \
  solarisfixes.h rio.h sds.h connection.h ae.h monotonic.h commands.h \
  allocator_defrag.h dict.h mt19937-64.h hashtable.h kvstore.h adlist.h \
  zmalloc.h anet.h version.h util.h latency.h trace/trace.h \
  trace/trace_aof.h trace/trace_cluster.h trace/trace_server.h \
  trace/trace_db.h trace/trace_rdb.h trace/trace_commands.h sparkline.h \
  quicklist.h expire.h rax.h memory_prefetch.h vset.h entry.h lrulfu.h \
  valkeymodule.h zipmap.h ziplist.h sha1.h endianconv.h crc64.h stream.h \
  listpack.h rdb.h serverassert.h
anet.o: anet.c fmacros.h anet.h config.h util.h sds.h serverassert.h
aof.o: aof.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
  connection.h ae.h monotonic.h commands.h allocator_defrag.h dict.h \
  mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h version.h \
  util.h latency.h trace/trace.h trace/trace_aof.h trace/trace_cluster.h \
  trace/trace_server.h trace/trace_db.h trace/trace_rdb.h \
  trace/trace_commands.h sparkline.h quicklist.h expire.h rax.h \
  memory_prefetch.h vset.h entry.h lrulfu.h valkeymodule.h zipmap.h \
  ziplist.h sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h bio.h \
  functions.h scripting_engine.h script.h module.h
bio.o: bio.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
  connection.h ae.h monotonic.h commands.h allocator_defrag.h dict.h \
  mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h version.h \
  util.h latency.h trace/trace.h trace/trace_aof.h trace/trace_cluster.h \
  trace/trace_server.h trace/trace_db.h trace/trace_rdb.h \
  trace/trace_commands.h sparkline.h quicklist.h expire.h rax.h \
  memory_prefetch.h vset.h entry.h lrulfu.h valkeymodule.h zipmap.h \
  ziplist.h sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h bio.h \
  mutexqueue.h fifo.h tls.h
bitops.o: bitops.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
  connection.h ae.h monotonic.h commands.h allocator_defrag.h dict.h \
  mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h version.h \
  util.h latency.h trace/trace.h trace/trace_aof.h trace/trace_cluster.h \
  trace/trace_server.h trace/trace_db.h trace/trace_rdb.h \
  trace/trace_commands.h sparkline.h quicklist.h expire.h rax.h \
  memory_prefetch.h vset.h entry.h lrulfu.h valkeymodule.h zipmap.h \
  ziplist.h sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h
blocked.o: blocked.c server.h fmacros.h config.h solarisfixes.h rio.h \
  sds.h connection.h ae.h monotonic.h commands.h allocator_defrag.h \
  dict.h mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h \
  version.h util.h latency.h trace/trace.h trace/trace_aof.h \
  trace/trace_cluster.h trace/trace_server.h trace/trace_db.h \
  trace/trace_rdb.h trace/trace_commands.h sparkline.h quicklist.h \
  expire.h rax.h memory_prefetch.h vset.h entry.h lrulfu.h \
  valkeymodule.h zipmap.h ziplist.h sha1.h endianconv.h crc64.h stream.h \
  listpack.h rdb.h commandlog.h cluster_slot_stats.h cluster.h \
  cluster_legacy.h module.h
call_reply.o: call_reply.c server.h fmacros.h config.h solarisfixes.h \
  rio.h sds.h connection.h ae.h monotonic.h commands.h \
  allocator_defrag.h dict.h mt19937-64.h hashtable.h kvstore.h adlist.h \
  zmalloc.h anet.h version.h util.h latency.h trace/trace.h \
  trace/trace_aof.h trace/trace_cluster.h trace/trace_server.h \
  trace/trace_db.h trace/trace_rdb.h trace/trace_commands.h sparkline.h \
  quicklist.h expire.h rax.h memory_prefetch.h vset.h entry.h lrulfu.h \
  valkeymodule.h zipmap.h ziplist.h sha1.h endianconv.h crc64.h stream.h \
  listpack.h rdb.h call_reply.h resp_parser.h
childinfo.o: childinfo.c server.h fmacros.h config.h solarisfixes.h rio.h \
  sds.h connection.h ae.h monotonic.h commands.h allocator_defrag.h \
  dict.h mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h \
  version.h util.h latency.h trace/trace.h trace/trace_aof.h \
  trace/trace_cluster.h trace/trace_server.h trace/trace_db.h \
  trace/trace_rdb.h trace/trace_commands.h sparkline.h quicklist.h \
  expire.h rax.h memory_prefetch.h vset.h entry.h lrulfu.h \
  valkeymodule.h zipmap.h ziplist.h sha1.h endianconv.h crc64.h stream.h \
  listpack.h rdb.h
cli_commands.o: cli_commands.c cli_commands.h commands.h commands.def
cli_common.o: cli_common.c fmacros.h cli_common.h \
  ../deps/libvalkey/include/valkey/valkey.h \
  ../deps/libvalkey/include/valkey/read.h \
  ../deps/libvalkey/include/valkey/visibility.h \
  ../deps/libvalkey/include/valkey/alloc.h sds.h version.h
cluster.o: cluster.c server.h fmacros.h config.h solarisfixes.h rio.h \
  sds.h connection.h ae.h monotonic.h commands.h allocator_defrag.h \
  dict.h mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h \
  version.h util.h latency.h trace/trace.h trace/trace_aof.h \
  trace/trace_cluster.h trace/trace_server.h trace/trace_db.h \
  trace/trace_rdb.h trace/trace_commands.h sparkline.h quicklist.h \
  expire.h rax.h memory_prefetch.h vset.h entry.h lrulfu.h \
  valkeymodule.h zipmap.h ziplist.h sha1.h endianconv.h crc64.h stream.h \
  listpack.h rdb.h cluster.h cluster_slot_stats.h cluster_legacy.h \
  module.h crc16_slottable.h
cluster_legacy.o: cluster_legacy.c server.h fmacros.h config.h \
  solarisfixes.h rio.h sds.h connection.h ae.h monotonic.h commands.h \
  allocator_defrag.h dict.h mt19937-64.h hashtable.h kvstore.h adlist.h \
  zmalloc.h anet.h version.h util.h latency.h trace/trace.h \
  trace/trace_aof.h trace/trace_cluster.h trace/trace_server.h \
  trace/trace_db.h trace/trace_rdb.h trace/trace_commands.h sparkline.h \
  quicklist.h expire.h rax.h memory_prefetch.h vset.h entry.h lrulfu.h \
  valkeymodule.h zipmap.h ziplist.h sha1.h endianconv.h crc64.h stream.h \
  listpack.h rdb.h cluster.h cluster_legacy.h cluster_slot_stats.h \
  cluster_migrateslots.h module.h
cluster_migrateslots.o: cluster_migrateslots.c cluster_migrateslots.h \
  server.h fmacros.h config.h solarisfixes.h rio.h sds.h connection.h \
  ae.h monotonic.h commands.h allocator_defrag.h dict.h mt19937-64.h \
  hashtable.h kvstore.h adlist.h zmalloc.h anet.h version.h util.h \
  latency.h trace/trace.h trace/trace_aof.h trace/trace_cluster.h \
  trace/trace_server.h trace/trace_db.h trace/trace_rdb.h \
  trace/trace_commands.h sparkline.h quicklist.h expire.h rax.h \
  memory_prefetch.h vset.h entry.h lrulfu.h valkeymodule.h zipmap.h \
  ziplist.h sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h \
  cluster.h cluster_legacy.h bio.h module.h functions.h \
  scripting_engine.h script.h
cluster_slot_stats.o: cluster_slot_stats.c cluster_slot_stats.h server.h \
  fmacros.h config.h solarisfixes.h rio.h sds.h connection.h ae.h \
  monotonic.h commands.h allocator_defrag.h dict.h mt19937-64.h \
  hashtable.h kvstore.h adlist.h zmalloc.h anet.h version.h util.h \
  latency.h trace/trace.h trace/trace_aof.h trace/trace_cluster.h \
  trace/trace_server.h trace/trace_db.h trace/trace_rdb.h \
  trace/trace_commands.h sparkline.h quicklist.h expire.h rax.h \
  memory_prefetch.h vset.h entry.h lrulfu.h valkeymodule.h zipmap.h \
  ziplist.h sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h \
  cluster.h cluster_legacy.h
commandlog.o: commandlog.c commandlog.h server.h fmacros.h config.h \
  solarisfixes.h rio.h sds.h connection.h ae.h monotonic.h commands.h \
  allocator_defrag.h dict.h mt19937-64.h hashtable.h kvstore.h adlist.h \
  zmalloc.h anet.h version.h util.h latency.h trace/trace.h \
  trace/trace_aof.h trace/trace_cluster.h trace/trace_server.h \
  trace/trace_db.h trace/trace_rdb.h trace/trace_commands.h sparkline.h \
  quicklist.h expire.h rax.h memory_prefetch.h vset.h entry.h lrulfu.h \
  valkeymodule.h zipmap.h ziplist.h sha1.h endianconv.h crc64.h stream.h \
  listpack.h rdb.h script.h scripting_engine.h
commands.o: commands.c commands.h server.h fmacros.h config.h \
  solarisfixes.h rio.h sds.h connection.h ae.h monotonic.h \
  allocator_defrag.h dict.h mt19937-64.h hashtable.h kvstore.h adlist.h \
  zmalloc.h anet.h version.h util.h latency.h trace/trace.h \
  trace/trace_aof.h trace/trace_cluster.h trace/trace_server.h \
  trace/trace_db.h trace/trace_rdb.h trace/trace_commands.h sparkline.h \
  quicklist.h expire.h rax.h memory_prefetch.h vset.h entry.h lrulfu.h \
  valkeymodule.h zipmap.h ziplist.h sha1.h endianconv.h crc64.h stream.h \
  listpack.h rdb.h commands.def
config.o: config.c io_threads.h server.h fmacros.h config.h \
  solarisfixes.h rio.h sds.h connection.h ae.h monotonic.h commands.h \
  allocator_defrag.h dict.h mt19937-64.h hashtable.h kvstore.h adlist.h \
  zmalloc.h anet.h version.h util.h latency.h trace/trace.h \
  trace/trace_aof.h trace/trace_cluster.h trace/trace_server.h \
  trace/trace_db.h trace/trace_rdb.h trace/trace_commands.h sparkline.h \
  quicklist.h expire.h rax.h memory_prefetch.h vset.h entry.h lrulfu.h \
  valkeymodule.h zipmap.h ziplist.h sha1.h endianconv.h crc64.h stream.h \
  listpack.h rdb.h cluster.h bio.h module.h cluster_migrateslots.h \
  cluster_legacy.h eval.h
connection.o: connection.c server.h fmacros.h config.h solarisfixes.h \
  rio.h sds.h connection.h ae.h monotonic.h commands.h \
  allocator_defrag.h dict.h mt19937-64.h hashtable.h kvstore.h adlist.h \
  zmalloc.h anet.h version.h util.h latency.h trace/trace.h \
  trace/trace_aof.h trace/trace_cluster.h trace/trace_server.h \
  trace/trace_db.h trace/trace_rdb.h trace/trace_commands.h sparkline.h \
  quicklist.h expire.h rax.h memory_prefetch.h vset.h entry.h lrulfu.h \
  valkeymodule.h zipmap.h ziplist.h sha1.h endianconv.h crc64.h stream.h \
  listpack.h rdb.h
crc16.o: crc16.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
  connection.h ae.h monotonic.h commands.h allocator_defrag.h dict.h \
  mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h version.h \
  util.h latency.h trace/trace.h trace/trace_aof.h trace/trace_cluster.h \
  trace/trace_server.h trace/trace_db.h trace/trace_rdb.h \
  trace/trace_commands.h sparkline.h quicklist.h expire.h rax.h \
  memory_prefetch.h vset.h entry.h lrulfu.h valkeymodule.h zipmap.h \
  ziplist.h sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h
crc16_slottable.o: crc16_slottable.c crc16_slottable.h
crc64.o: crc64.c crc64.h crcspeed.h serverassert.h
crccombine.o: crccombine.c crccombine.h
crcspeed.o: crcspeed.c crcspeed.h crccombine.h
db.o: db.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
  connection.h ae.h monotonic.h commands.h allocator_defrag.h dict.h \
  mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h version.h \
  util.h latency.h trace/trace.h trace/trace_aof.h trace/trace_cluster.h \
  trace/trace_server.h trace/trace_db.h trace/trace_rdb.h \
  trace/trace_commands.h sparkline.h quicklist.h expire.h rax.h \
  memory_prefetch.h vset.h entry.h lrulfu.h valkeymodule.h zipmap.h \
  ziplist.h sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h \
  cluster.h cluster_migrateslots.h cluster_legacy.h script.h \
  scripting_engine.h functions.h io_threads.h module.h vector.h \
  core/nexstorage.h
debug.o: debug.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
  connection.h ae.h monotonic.h commands.h allocator_defrag.h dict.h \
  mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h version.h \
  util.h latency.h trace/trace.h trace/trace_aof.h trace/trace_cluster.h \
  trace/trace_server.h trace/trace_db.h trace/trace_rdb.h \
  trace/trace_commands.h sparkline.h quicklist.h expire.h rax.h \
  memory_prefetch.h vset.h entry.h lrulfu.h valkeymodule.h zipmap.h \
  ziplist.h sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h bio.h \
  ../deps/fpconv/fpconv_dtoa.h cluster.h threads_mngr.h io_threads.h \
  module.h valkey_strtod.h
defrag.o: defrag.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
  connection.h ae.h monotonic.h commands.h allocator_defrag.h dict.h \
  mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h version.h \
  util.h latency.h trace/trace.h trace/trace_aof.h trace/trace_cluster.h \
  trace/trace_server.h trace/trace_db.h trace/trace_rdb.h \
  trace/trace_commands.h sparkline.h quicklist.h expire.h rax.h \
  memory_prefetch.h vset.h entry.h lrulfu.h valkeymodule.h zipmap.h \
  ziplist.h sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h eval.h \
  script.h scripting_engine.h module.h
dict.o: dict.c fmacros.h dict.h mt19937-64.h zmalloc.h serverassert.h \
  monotonic.h config.h util.h sds.h
entry.o: entry.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
  connection.h ae.h monotonic.h commands.h allocator_defrag.h dict.h \
  mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h version.h \
  util.h latency.h trace/trace.h trace/trace_aof.h trace/trace_cluster.h \
  trace/trace_server.h trace/trace_db.h trace/trace_rdb.h \
  trace/trace_commands.h sparkline.h quicklist.h expire.h rax.h \
  memory_prefetch.h vset.h entry.h lrulfu.h valkeymodule.h zipmap.h \
  ziplist.h sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h \
  serverassert.h
eval.o: eval.c eval.h server.h fmacros.h config.h solarisfixes.h rio.h \
  sds.h connection.h ae.h monotonic.h commands.h allocator_defrag.h \
  dict.h mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h \
  version.h util.h latency.h trace/trace.h trace/trace_aof.h \
  trace/trace_cluster.h trace/trace_server.h trace/trace_db.h \
  trace/trace_rdb.h trace/trace_commands.h sparkline.h quicklist.h \
  expire.h rax.h memory_prefetch.h vset.h entry.h lrulfu.h \
  valkeymodule.h zipmap.h ziplist.h sha1.h endianconv.h crc64.h stream.h \
  listpack.h rdb.h rand.h cluster.h resp_parser.h script.h \
  scripting_engine.h
evict.o: evict.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
  connection.h ae.h monotonic.h commands.h allocator_defrag.h dict.h \
  mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h version.h \
  util.h latency.h trace/trace.h trace/trace_aof.h trace/trace_cluster.h \
  trace/trace_server.h trace/trace_db.h trace/trace_rdb.h \
  trace/trace_commands.h sparkline.h quicklist.h expire.h rax.h \
  memory_prefetch.h vset.h entry.h lrulfu.h valkeymodule.h zipmap.h \
  ziplist.h sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h bio.h \
  script.h scripting_engine.h cluster_migrateslots.h cluster.h \
  cluster_legacy.h
expire.o: expire.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
  connection.h ae.h monotonic.h commands.h allocator_defrag.h dict.h \
  mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h version.h \
  util.h latency.h trace/trace.h trace/trace_aof.h trace/trace_cluster.h \
  trace/trace_server.h trace/trace_db.h trace/trace_rdb.h \
  trace/trace_commands.h sparkline.h quicklist.h expire.h rax.h \
  memory_prefetch.h vset.h entry.h lrulfu.h valkeymodule.h zipmap.h \
  ziplist.h sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h \
  cluster.h cluster_migrateslots.h cluster_legacy.h
fifo.o: fifo.c fifo.h serverassert.h zmalloc.h
functions.o: functions.c functions.h server.h fmacros.h config.h \
  solarisfixes.h rio.h sds.h connection.h ae.h monotonic.h commands.h \
  allocator_defrag.h dict.h mt19937-64.h hashtable.h kvstore.h adlist.h \
  zmalloc.h anet.h version.h util.h latency.h trace/trace.h \
  trace/trace_aof.h trace/trace_cluster.h trace/trace_server.h \
  trace/trace_db.h trace/trace_rdb.h trace/trace_commands.h sparkline.h \
  quicklist.h expire.h rax.h memory_prefetch.h vset.h entry.h lrulfu.h \
  valkeymodule.h zipmap.h ziplist.h sha1.h endianconv.h crc64.h stream.h \
  listpack.h rdb.h scripting_engine.h script.h
fuzzer_client.o: fuzzer_client.c \
  ../deps/libvalkey/include/valkey/valkey.h \
  ../deps/libvalkey/include/valkey/read.h \
  ../deps/libvalkey/include/valkey/visibility.h \
  ../deps/libvalkey/include/valkey/alloc.h fuzzer_command_generator.h \
  sds.h adlist.h cli_common.h
fuzzer_command_generator.o: fuzzer_command_generator.c fmacros.h \
  ../deps/libvalkey/include/valkey/valkey.h \
  ../deps/libvalkey/include/valkey/read.h \
  ../deps/libvalkey/include/valkey/visibility.h \
  ../deps/libvalkey/include/valkey/alloc.h commands.h \
  fuzzer_command_generator.h sds.h dict.h mt19937-64.h server.h config.h \
  solarisfixes.h rio.h connection.h ae.h monotonic.h allocator_defrag.h \
  hashtable.h kvstore.h adlist.h zmalloc.h anet.h version.h util.h \
  latency.h trace/trace.h trace/trace_aof.h trace/trace_cluster.h \
  trace/trace_server.h trace/trace_db.h trace/trace_rdb.h \
  trace/trace_commands.h sparkline.h quicklist.h expire.h rax.h \
  memory_prefetch.h vset.h entry.h lrulfu.h valkeymodule.h zipmap.h \
  ziplist.h sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h
geo.o: geo.c geo.h server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
  connection.h ae.h monotonic.h commands.h allocator_defrag.h dict.h \
  mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h version.h \
  util.h latency.h trace/trace.h trace/trace_aof.h trace/trace_cluster.h \
  trace/trace_server.h trace/trace_db.h trace/trace_rdb.h \
  trace/trace_commands.h sparkline.h quicklist.h expire.h rax.h \
  memory_prefetch.h vset.h entry.h lrulfu.h valkeymodule.h zipmap.h \
  ziplist.h sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h \
  geohash_helper.h geohash.h debugmacro.h pqsort.h
geohash.o: geohash.c geohash.h
geohash_helper.o: geohash_helper.c fmacros.h geohash_helper.h geohash.h \
  debugmacro.h
hashtable.o: hashtable.c hashtable.h fmacros.h serverassert.h zmalloc.h \
  mt19937-64.h monotonic.h config.h util.h sds.h
hyperloglog.o: hyperloglog.c server.h fmacros.h config.h solarisfixes.h \
  rio.h sds.h connection.h ae.h monotonic.h commands.h \
  allocator_defrag.h dict.h mt19937-64.h hashtable.h kvstore.h adlist.h \
  zmalloc.h anet.h version.h util.h latency.h trace/trace.h \
  trace/trace_aof.h trace/trace_cluster.h trace/trace_server.h \
  trace/trace_db.h trace/trace_rdb.h trace/trace_commands.h sparkline.h \
  quicklist.h expire.h rax.h memory_prefetch.h vset.h entry.h lrulfu.h \
  valkeymodule.h zipmap.h ziplist.h sha1.h endianconv.h crc64.h stream.h \
  listpack.h rdb.h intrinsics.h
intset.o: intset.c intset.h zmalloc.h endianconv.h config.h \
  serverassert.h
io_threads.o: io_threads.c io_threads.h server.h fmacros.h config.h \
  solarisfixes.h rio.h sds.h connection.h ae.h monotonic.h commands.h \
  allocator_defrag.h dict.h mt19937-64.h hashtable.h kvstore.h adlist.h \
  zmalloc.h anet.h version.h util.h latency.h trace/trace.h \
  trace/trace_aof.h trace/trace_cluster.h trace/trace_server.h \
  trace/trace_db.h trace/trace_rdb.h trace/trace_commands.h sparkline.h \
  quicklist.h expire.h rax.h memory_prefetch.h vset.h entry.h lrulfu.h \
  valkeymodule.h zipmap.h ziplist.h sha1.h endianconv.h crc64.h stream.h \
  listpack.h rdb.h
kvstore.o: kvstore.c fmacros.h zmalloc.h kvstore.h hashtable.h adlist.h \
  serverassert.h dict.h mt19937-64.h monotonic.h
latency.o: latency.c server.h fmacros.h config.h solarisfixes.h rio.h \
  sds.h connection.h ae.h monotonic.h commands.h allocator_defrag.h \
  dict.h mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h \
  version.h util.h latency.h trace/trace.h trace/trace_aof.h \
  trace/trace_cluster.h trace/trace_server.h trace/trace_db.h \
  trace/trace_rdb.h trace/trace_commands.h sparkline.h quicklist.h \
  expire.h rax.h memory_prefetch.h vset.h entry.h lrulfu.h \
  valkeymodule.h zipmap.h ziplist.h sha1.h endianconv.h crc64.h stream.h \
  listpack.h rdb.h ../deps/hdr_histogram/hdr_histogram.h
lazyfree.o: lazyfree.c server.h fmacros.h config.h solarisfixes.h rio.h \
  sds.h connection.h ae.h monotonic.h commands.h allocator_defrag.h \
  dict.h mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h \
  version.h util.h latency.h trace/trace.h trace/trace_aof.h \
  trace/trace_cluster.h trace/trace_server.h trace/trace_db.h \
  trace/trace_rdb.h trace/trace_commands.h sparkline.h quicklist.h \
  expire.h rax.h memory_prefetch.h vset.h entry.h lrulfu.h \
  valkeymodule.h zipmap.h ziplist.h sha1.h endianconv.h crc64.h stream.h \
  listpack.h rdb.h bio.h functions.h scripting_engine.h script.h \
  cluster.h module.h
listpack.o: listpack.c listpack.h listpack_malloc.h zmalloc.h \
  serverassert.h util.h sds.h config.h
localtime.o: localtime.c
logreqres.o: logreqres.c server.h fmacros.h config.h solarisfixes.h rio.h \
  sds.h connection.h ae.h monotonic.h commands.h allocator_defrag.h \
  dict.h mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h \
  version.h util.h latency.h trace/trace.h trace/trace_aof.h \
  trace/trace_cluster.h trace/trace_server.h trace/trace_db.h \
  trace/trace_rdb.h trace/trace_commands.h sparkline.h quicklist.h \
  expire.h rax.h memory_prefetch.h vset.h entry.h lrulfu.h \
  valkeymodule.h zipmap.h ziplist.h sha1.h endianconv.h crc64.h stream.h \
  listpack.h rdb.h
lolwut.o: lolwut.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
  connection.h ae.h monotonic.h commands.h allocator_defrag.h dict.h \
  mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h version.h \
  util.h latency.h trace/trace.h trace/trace_aof.h trace/trace_cluster.h \
  trace/trace_server.h trace/trace_db.h trace/trace_rdb.h \
  trace/trace_commands.h sparkline.h quicklist.h expire.h rax.h \
  memory_prefetch.h vset.h entry.h lrulfu.h valkeymodule.h zipmap.h \
  ziplist.h sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h \
  lolwut.h
lolwut5.o: lolwut5.c server.h fmacros.h config.h solarisfixes.h rio.h \
  sds.h connection.h ae.h monotonic.h commands.h allocator_defrag.h \
  dict.h mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h \
  version.h util.h latency.h trace/trace.h trace/trace_aof.h \
  trace/trace_cluster.h trace/trace_server.h trace/trace_db.h \
  trace/trace_rdb.h trace/trace_commands.h sparkline.h quicklist.h \
  expire.h rax.h memory_prefetch.h vset.h entry.h lrulfu.h \
  valkeymodule.h zipmap.h ziplist.h sha1.h endianconv.h crc64.h stream.h \
  listpack.h rdb.h lolwut.h
lolwut6.o: lolwut6.c server.h fmacros.h config.h solarisfixes.h rio.h \
  sds.h connection.h ae.h monotonic.h commands.h allocator_defrag.h \
  dict.h mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h \
  version.h util.h latency.h trace/trace.h trace/trace_aof.h \
  trace/trace_cluster.h trace/trace_server.h trace/trace_db.h \
  trace/trace_rdb.h trace/trace_commands.h sparkline.h quicklist.h \
  expire.h rax.h memory_prefetch.h vset.h entry.h lrulfu.h \
  valkeymodule.h zipmap.h ziplist.h sha1.h endianconv.h crc64.h stream.h \
  listpack.h rdb.h lolwut.h
lolwut9.o: lolwut9.c server.h fmacros.h config.h solarisfixes.h rio.h \
  sds.h connection.h ae.h monotonic.h commands.h allocator_defrag.h \
  dict.h mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h \
  version.h util.h latency.h trace/trace.h trace/trace_aof.h \
  trace/trace_cluster.h trace/trace_server.h trace/trace_db.h \
  trace/trace_rdb.h trace/trace_commands.h sparkline.h quicklist.h \
  expire.h rax.h memory_prefetch.h vset.h entry.h lrulfu.h \
  valkeymodule.h zipmap.h ziplist.h sha1.h endianconv.h crc64.h stream.h \
  listpack.h rdb.h lolwut.h
lrulfu.o: lrulfu.c lrulfu.h fmacros.h
lzf_c.o: lzf_c.c lzfP.h
lzf_d.o: lzf_d.c lzfP.h
memory_prefetch.o: memory_prefetch.c memory_prefetch.h server.h fmacros.h \
  config.h solarisfixes.h rio.h sds.h connection.h ae.h monotonic.h \
  commands.h allocator_defrag.h dict.h mt19937-64.h hashtable.h \
  kvstore.h adlist.h zmalloc.h anet.h version.h util.h latency.h \
  trace/trace.h trace/trace_aof.h trace/trace_cluster.h \
  trace/trace_server.h trace/trace_db.h trace/trace_rdb.h \
  trace/trace_commands.h sparkline.h quicklist.h expire.h rax.h vset.h \
  entry.h lrulfu.h valkeymodule.h zipmap.h ziplist.h sha1.h endianconv.h \
  crc64.h stream.h listpack.h rdb.h io_threads.h
memtest.o: memtest.c config.h serverassert.h
module.o: module.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
  connection.h ae.h monotonic.h commands.h allocator_defrag.h dict.h \
  mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h version.h \
  util.h latency.h trace/trace.h trace/trace_aof.h trace/trace_cluster.h \
  trace/trace_server.h trace/trace_db.h trace/trace_rdb.h \
  trace/trace_commands.h sparkline.h quicklist.h expire.h rax.h \
  memory_prefetch.h vset.h entry.h lrulfu.h valkeymodule.h zipmap.h \
  ziplist.h sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h \
  cluster.h commandlog.h script.h scripting_engine.h call_reply.h \
  resp_parser.h ../deps/hdr_histogram/hdr_histogram.h crc16_slottable.h \
  module.h io_threads.h cluster_migrateslots.h cluster_legacy.h
monotonic.o: monotonic.c monotonic.h fmacros.h serverassert.h
mt19937-64.o: mt19937-64.c mt19937-64.h
multi.o: multi.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
  connection.h ae.h monotonic.h commands.h allocator_defrag.h dict.h \
  mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h version.h \
  util.h latency.h trace/trace.h trace/trace_aof.h trace/trace_cluster.h \
  trace/trace_server.h trace/trace_db.h trace/trace_rdb.h \
  trace/trace_commands.h sparkline.h quicklist.h expire.h rax.h \
  memory_prefetch.h vset.h entry.h lrulfu.h valkeymodule.h zipmap.h \
  ziplist.h sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h
mutexqueue.o: mutexqueue.c mutexqueue.h fifo.h serverassert.h zmalloc.h
networking.o: networking.c server.h fmacros.h config.h solarisfixes.h \
  rio.h sds.h connection.h ae.h monotonic.h commands.h \
  allocator_defrag.h dict.h mt19937-64.h hashtable.h kvstore.h adlist.h \
  zmalloc.h anet.h version.h util.h latency.h trace/trace.h \
  trace/trace_aof.h trace/trace_cluster.h trace/trace_server.h \
  trace/trace_db.h trace/trace_rdb.h trace/trace_commands.h sparkline.h \
  quicklist.h expire.h rax.h memory_prefetch.h vset.h entry.h lrulfu.h \
  valkeymodule.h zipmap.h ziplist.h sha1.h endianconv.h crc64.h stream.h \
  listpack.h rdb.h cluster.h cluster_slot_stats.h cluster_legacy.h \
  cluster_migrateslots.h script.h scripting_engine.h intset.h \
  ../deps/fpconv/fpconv_dtoa.h fmtargs.h io_threads.h module.h
notify.o: notify.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
  connection.h ae.h monotonic.h commands.h allocator_defrag.h dict.h \
  mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h version.h \
  util.h latency.h trace/trace.h trace/trace_aof.h trace/trace_cluster.h \
  trace/trace_server.h trace/trace_db.h trace/trace_rdb.h \
  trace/trace_commands.h sparkline.h quicklist.h expire.h rax.h \
  memory_prefetch.h vset.h entry.h lrulfu.h valkeymodule.h zipmap.h \
  ziplist.h sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h \
  module.h
object.o: object.c hashtable.h fmacros.h server.h config.h solarisfixes.h \
  rio.h sds.h connection.h ae.h monotonic.h commands.h \
  allocator_defrag.h dict.h mt19937-64.h kvstore.h adlist.h zmalloc.h \
  anet.h version.h util.h latency.h trace/trace.h trace/trace_aof.h \
  trace/trace_cluster.h trace/trace_server.h trace/trace_db.h \
  trace/trace_rdb.h trace/trace_commands.h sparkline.h quicklist.h \
  expire.h rax.h memory_prefetch.h vset.h entry.h lrulfu.h \
  valkeymodule.h zipmap.h ziplist.h sha1.h endianconv.h crc64.h stream.h \
  listpack.h rdb.h serverassert.h functions.h scripting_engine.h \
  script.h intset.h module.h
pqsort.o: pqsort.c
pubsub.o: pubsub.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
  connection.h ae.h monotonic.h commands.h allocator_defrag.h dict.h \
  mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h version.h \
  util.h latency.h trace/trace.h trace/trace_aof.h trace/trace_cluster.h \
  trace/trace_server.h trace/trace_db.h trace/trace_rdb.h \
  trace/trace_commands.h sparkline.h quicklist.h expire.h rax.h \
  memory_prefetch.h vset.h entry.h lrulfu.h valkeymodule.h zipmap.h \
  ziplist.h sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h \
  cluster.h cluster_slot_stats.h cluster_legacy.h
quicklist.o: quicklist.c quicklist.h zmalloc.h config.h listpack.h util.h \
  sds.h lzf.h serverassert.h
rand.o: rand.c
rax.o: rax.c rax.h serverassert.h rax_malloc.h zmalloc.h
rdb.o: rdb.c hashtable.h fmacros.h server.h config.h solarisfixes.h rio.h \
  sds.h connection.h ae.h monotonic.h commands.h allocator_defrag.h \
  dict.h mt19937-64.h kvstore.h adlist.h zmalloc.h anet.h version.h \
  util.h latency.h trace/trace.h trace/trace_aof.h trace/trace_cluster.h \
  trace/trace_server.h trace/trace_db.h trace/trace_rdb.h \
  trace/trace_commands.h sparkline.h quicklist.h expire.h rax.h \
  memory_prefetch.h vset.h entry.h lrulfu.h valkeymodule.h zipmap.h \
  ziplist.h sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h lzf.h \
  ../deps/fpconv/fpconv_dtoa.h functions.h scripting_engine.h script.h \
  intset.h bio.h module.h cluster.h cluster_migrateslots.h \
  cluster_legacy.h
rdma.o: rdma.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
  connection.h ae.h monotonic.h commands.h allocator_defrag.h dict.h \
  mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h version.h \
  util.h latency.h trace/trace.h trace/trace_aof.h trace/trace_cluster.h \
  trace/trace_server.h trace/trace_db.h trace/trace_rdb.h \
  trace/trace_commands.h sparkline.h quicklist.h expire.h rax.h \
  memory_prefetch.h vset.h entry.h lrulfu.h valkeymodule.h zipmap.h \
  ziplist.h sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h \
  serverassert.h
release.o: release.c release.h version.h crc64.h
replication.o: replication.c server.h fmacros.h config.h solarisfixes.h \
  rio.h sds.h connection.h ae.h monotonic.h commands.h \
  allocator_defrag.h dict.h mt19937-64.h hashtable.h kvstore.h adlist.h \
  zmalloc.h anet.h version.h util.h latency.h trace/trace.h \
  trace/trace_aof.h trace/trace_cluster.h trace/trace_server.h \
  trace/trace_db.h trace/trace_rdb.h trace/trace_commands.h sparkline.h \
  quicklist.h expire.h rax.h memory_prefetch.h vset.h entry.h lrulfu.h \
  valkeymodule.h zipmap.h ziplist.h sha1.h endianconv.h crc64.h stream.h \
  listpack.h rdb.h cluster.h cluster_slot_stats.h cluster_legacy.h bio.h \
  functions.h scripting_engine.h script.h module.h \
  cluster_migrateslots.h
resp_parser.o: resp_parser.c resp_parser.h server.h fmacros.h config.h \
  solarisfixes.h rio.h sds.h connection.h ae.h monotonic.h commands.h \
  allocator_defrag.h dict.h mt19937-64.h hashtable.h kvstore.h adlist.h \
  zmalloc.h anet.h version.h util.h latency.h trace/trace.h \
  trace/trace_aof.h trace/trace_cluster.h trace/trace_server.h \
  trace/trace_db.h trace/trace_rdb.h trace/trace_commands.h sparkline.h \
  quicklist.h expire.h rax.h memory_prefetch.h vset.h entry.h lrulfu.h \
  valkeymodule.h zipmap.h ziplist.h sha1.h endianconv.h crc64.h stream.h \
  listpack.h rdb.h valkey_strtod.h
rio.o: rio.c fmacros.h ../deps/fpconv/fpconv_dtoa.h rio.h sds.h \
  connection.h ae.h monotonic.h util.h crc64.h config.h server.h \
  solarisfixes.h commands.h allocator_defrag.h dict.h mt19937-64.h \
  hashtable.h kvstore.h adlist.h zmalloc.h anet.h version.h latency.h \
  trace/trace.h trace/trace_aof.h trace/trace_cluster.h \
  trace/trace_server.h trace/trace_db.h trace/trace_rdb.h \
  trace/trace_commands.h sparkline.h quicklist.h expire.h rax.h \
  memory_prefetch.h vset.h entry.h lrulfu.h valkeymodule.h zipmap.h \
  ziplist.h sha1.h endianconv.h stream.h listpack.h rdb.h connhelpers.h
script.o: script.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
  connection.h ae.h monotonic.h commands.h allocator_defrag.h dict.h \
  mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h version.h \
  util.h latency.h trace/trace.h trace/trace_aof.h trace/trace_cluster.h \
  trace/trace_server.h trace/trace_db.h trace/trace_rdb.h \
  trace/trace_commands.h sparkline.h quicklist.h expire.h rax.h \
  memory_prefetch.h vset.h entry.h lrulfu.h valkeymodule.h zipmap.h \
  ziplist.h sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h \
  script.h scripting_engine.h cluster_slot_stats.h cluster.h \
  cluster_legacy.h
scripting_engine.o: scripting_engine.c scripting_engine.h server.h \
  fmacros.h config.h solarisfixes.h rio.h sds.h connection.h ae.h \
  monotonic.h commands.h allocator_defrag.h dict.h mt19937-64.h \
  hashtable.h kvstore.h adlist.h zmalloc.h anet.h version.h util.h \
  latency.h trace/trace.h trace/trace_aof.h trace/trace_cluster.h \
  trace/trace_server.h trace/trace_db.h trace/trace_rdb.h \
  trace/trace_commands.h sparkline.h quicklist.h expire.h rax.h \
  memory_prefetch.h vset.h entry.h lrulfu.h valkeymodule.h zipmap.h \
  ziplist.h sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h bio.h \
  functions.h script.h module.h
sds.o: sds.c serverassert.h sds.h sdsalloc.h zmalloc.h util.h
sentinel.o: sentinel.c server.h fmacros.h config.h solarisfixes.h rio.h \
  sds.h connection.h ae.h monotonic.h commands.h allocator_defrag.h \
  dict.h mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h \
  version.h util.h latency.h trace/trace.h trace/trace_aof.h \
  trace/trace_cluster.h trace/trace_server.h trace/trace_db.h \
  trace/trace_rdb.h trace/trace_commands.h sparkline.h quicklist.h \
  expire.h rax.h memory_prefetch.h vset.h entry.h lrulfu.h \
  valkeymodule.h zipmap.h ziplist.h sha1.h endianconv.h crc64.h stream.h \
  listpack.h rdb.h ../deps/libvalkey/include/valkey/valkey.h \
  ../deps/libvalkey/include/valkey/read.h \
  ../deps/libvalkey/include/valkey/visibility.h \
  ../deps/libvalkey/include/valkey/alloc.h \
  ../deps/libvalkey/include/valkey/async.h
server.o: server.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
  connection.h ae.h monotonic.h commands.h allocator_defrag.h dict.h \
  mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h version.h \
  util.h latency.h trace/trace.h trace/trace_aof.h trace/trace_cluster.h \
  trace/trace_server.h trace/trace_db.h trace/trace_rdb.h \
  trace/trace_commands.h sparkline.h quicklist.h expire.h rax.h \
  memory_prefetch.h vset.h entry.h lrulfu.h valkeymodule.h zipmap.h \
  ziplist.h sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h \
  cluster.h cluster_slot_stats.h cluster_legacy.h cluster_migrateslots.h \
  commandlog.h bio.h functions.h scripting_engine.h script.h \
  ../deps/hdr_histogram/hdr_histogram.h syscheck.h threads_mngr.h \
  fmtargs.h io_threads.h tls.h module.h eval.h core/nexstorage.h \
  asciilogo.h
serverassert.o: serverassert.c
setcpuaffinity.o: setcpuaffinity.c config.h
setproctitle.o: setproctitle.c
sha1.o: sha1.c solarisfixes.h sha1.h config.h
sha256.o: sha256.c sha256.h
siphash.o: siphash.c
socket.o: socket.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
  connection.h ae.h monotonic.h commands.h allocator_defrag.h dict.h \
  mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h version.h \
  util.h latency.h trace/trace.h trace/trace_aof.h trace/trace_cluster.h \
  trace/trace_server.h trace/trace_db.h trace/trace_rdb.h \
  trace/trace_commands.h sparkline.h quicklist.h expire.h rax.h \
  memory_prefetch.h vset.h entry.h lrulfu.h valkeymodule.h zipmap.h \
  ziplist.h sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h \
  connhelpers.h io_threads.h
sort.o: sort.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
  connection.h ae.h monotonic.h commands.h allocator_defrag.h dict.h \
  mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h version.h \
  util.h latency.h trace/trace.h trace/trace_aof.h trace/trace_cluster.h \
  trace/trace_server.h trace/trace_db.h trace/trace_rdb.h \
  trace/trace_commands.h sparkline.h quicklist.h expire.h rax.h \
  memory_prefetch.h vset.h entry.h lrulfu.h valkeymodule.h zipmap.h \
  ziplist.h sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h \
  pqsort.h cluster.h valkey_strtod.h
sparkline.o: sparkline.c server.h fmacros.h config.h solarisfixes.h rio.h \
  sds.h connection.h ae.h monotonic.h commands.h allocator_defrag.h \
  dict.h mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h \
  version.h util.h latency.h trace/trace.h trace/trace_aof.h \
  trace/trace_cluster.h trace/trace_server.h trace/trace_db.h \
  trace/trace_rdb.h trace/trace_commands.h sparkline.h quicklist.h \
  expire.h rax.h memory_prefetch.h vset.h entry.h lrulfu.h \
  valkeymodule.h zipmap.h ziplist.h sha1.h endianconv.h crc64.h stream.h \
  listpack.h rdb.h
strl.o: strl.c
syncio.o: syncio.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
  connection.h ae.h monotonic.h commands.h allocator_defrag.h dict.h \
  mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h version.h \
  util.h latency.h trace/trace.h trace/trace_aof.h trace/trace_cluster.h \
  trace/trace_server.h trace/trace_db.h trace/trace_rdb.h \
  trace/trace_commands.h sparkline.h quicklist.h expire.h rax.h \
  memory_prefetch.h vset.h entry.h lrulfu.h valkeymodule.h zipmap.h \
  ziplist.h sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h
syscheck.o: syscheck.c fmacros.h config.h syscheck.h sds.h anet.h
t_hash.o: t_hash.c hashtable.h fmacros.h rax.h sds.h vset.h util.h \
  server.h config.h solarisfixes.h rio.h connection.h ae.h monotonic.h \
  commands.h allocator_defrag.h dict.h mt19937-64.h kvstore.h adlist.h \
  zmalloc.h anet.h version.h latency.h trace/trace.h trace/trace_aof.h \
  trace/trace_cluster.h trace/trace_server.h trace/trace_db.h \
  trace/trace_rdb.h trace/trace_commands.h sparkline.h quicklist.h \
  expire.h memory_prefetch.h entry.h lrulfu.h valkeymodule.h zipmap.h \
  ziplist.h sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h
t_list.o: t_list.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
  connection.h ae.h monotonic.h commands.h allocator_defrag.h dict.h \
  mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h version.h \
  util.h latency.h trace/trace.h trace/trace_aof.h trace/trace_cluster.h \
  trace/trace_server.h trace/trace_db.h trace/trace_rdb.h \
  trace/trace_commands.h sparkline.h quicklist.h expire.h rax.h \
  memory_prefetch.h vset.h entry.h lrulfu.h valkeymodule.h zipmap.h \
  ziplist.h sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h
t_set.o: t_set.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
  connection.h ae.h monotonic.h commands.h allocator_defrag.h dict.h \
  mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h version.h \
  util.h latency.h trace/trace.h trace/trace_aof.h trace/trace_cluster.h \
  trace/trace_server.h trace/trace_db.h trace/trace_rdb.h \
  trace/trace_commands.h sparkline.h quicklist.h expire.h rax.h \
  memory_prefetch.h vset.h entry.h lrulfu.h valkeymodule.h zipmap.h \
  ziplist.h sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h \
  intset.h
t_stream.o: t_stream.c server.h fmacros.h config.h solarisfixes.h rio.h \
  sds.h connection.h ae.h monotonic.h commands.h allocator_defrag.h \
  dict.h mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h \
  version.h util.h latency.h trace/trace.h trace/trace_aof.h \
  trace/trace_cluster.h trace/trace_server.h trace/trace_db.h \
  trace/trace_rdb.h trace/trace_commands.h sparkline.h quicklist.h \
  expire.h rax.h memory_prefetch.h vset.h entry.h lrulfu.h \
  valkeymodule.h zipmap.h ziplist.h sha1.h endianconv.h crc64.h stream.h \
  listpack.h rdb.h
t_string.o: t_string.c server.h fmacros.h config.h solarisfixes.h rio.h \
  sds.h connection.h ae.h monotonic.h commands.h allocator_defrag.h \
  dict.h mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h \
  version.h util.h latency.h trace/trace.h trace/trace_aof.h \
  trace/trace_cluster.h trace/trace_server.h trace/trace_db.h \
  trace/trace_rdb.h trace/trace_commands.h sparkline.h quicklist.h \
  expire.h rax.h memory_prefetch.h vset.h entry.h lrulfu.h \
  valkeymodule.h zipmap.h ziplist.h sha1.h endianconv.h crc64.h stream.h \
  listpack.h rdb.h core/nexstorage.h
t_zset.o: t_zset.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
  connection.h ae.h monotonic.h commands.h allocator_defrag.h dict.h \
  mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h version.h \
  util.h latency.h trace/trace.h trace/trace_aof.h trace/trace_cluster.h \
  trace/trace_server.h trace/trace_db.h trace/trace_rdb.h \
  trace/trace_commands.h sparkline.h quicklist.h expire.h rax.h \
  memory_prefetch.h vset.h entry.h lrulfu.h valkeymodule.h zipmap.h \
  ziplist.h sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h \
  intset.h valkey_strtod.h
threads_mngr.o: threads_mngr.c threads_mngr.h fmacros.h
timeout.o: timeout.c server.h fmacros.h config.h solarisfixes.h rio.h \
  sds.h connection.h ae.h monotonic.h commands.h allocator_defrag.h \
  dict.h mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h \
  version.h util.h latency.h trace/trace.h trace/trace_aof.h \
  trace/trace_cluster.h trace/trace_server.h trace/trace_db.h \
  trace/trace_rdb.h trace/trace_commands.h sparkline.h quicklist.h \
  expire.h rax.h memory_prefetch.h vset.h entry.h lrulfu.h \
  valkeymodule.h zipmap.h ziplist.h sha1.h endianconv.h crc64.h stream.h \
  listpack.h rdb.h cluster.h
tls.o: tls.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
  connection.h ae.h monotonic.h commands.h allocator_defrag.h dict.h \
  mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h version.h \
  util.h latency.h trace/trace.h trace/trace_aof.h trace/trace_cluster.h \
  trace/trace_server.h trace/trace_db.h trace/trace_rdb.h \
  trace/trace_commands.h sparkline.h quicklist.h expire.h rax.h \
  memory_prefetch.h vset.h entry.h lrulfu.h valkeymodule.h zipmap.h \
  ziplist.h sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h \
  connhelpers.h io_threads.h bio.h
trace.o: trace/trace.c trace/trace.h trace/trace_aof.h \
  trace/trace_cluster.h trace/trace_server.h trace/trace_db.h \
  trace/trace_rdb.h trace/trace_commands.h
trace_aof.o: trace/trace_aof.c trace/trace_aof.h
trace_cluster.o: trace/trace_cluster.c trace/trace_cluster.h
trace_commands.o: trace/trace_commands.c trace/trace_commands.h
trace_db.o: trace/trace_db.c trace/trace_db.h
trace_rdb.o: trace/trace_rdb.c trace/trace_rdb.h
trace_server.o: trace/trace_server.c trace/trace_server.h
tracking.o: tracking.c server.h fmacros.h config.h solarisfixes.h rio.h \
  sds.h connection.h ae.h monotonic.h commands.h allocator_defrag.h \
  dict.h mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h \
  version.h util.h latency.h trace/trace.h trace/trace_aof.h \
  trace/trace_cluster.h trace/trace_server.h trace/trace_db.h \
  trace/trace_rdb.h trace/trace_commands.h sparkline.h quicklist.h \
  expire.h rax.h memory_prefetch.h vset.h entry.h lrulfu.h \
  valkeymodule.h zipmap.h ziplist.h sha1.h endianconv.h crc64.h stream.h \
  listpack.h rdb.h
unix.o: unix.c server.h fmacros.h config.h solarisfixes.h rio.h sds.h \
  connection.h ae.h monotonic.h commands.h allocator_defrag.h dict.h \
  mt19937-64.h hashtable.h kvstore.h adlist.h zmalloc.h anet.h version.h \
  util.h latency.h trace/trace.h trace/trace_aof.h trace/trace_cluster.h \
  trace/trace_server.h trace/trace_db.h trace/trace_rdb.h \
  trace/trace_commands.h sparkline.h quicklist.h expire.h rax.h \
  memory_prefetch.h vset.h entry.h lrulfu.h valkeymodule.h zipmap.h \
  ziplist.h sha1.h endianconv.h crc64.h stream.h listpack.h rdb.h
util.o: util.c fmacros.h ../deps/fpconv/fpconv_dtoa.h util.h sds.h \
  sha256.h config.h zmalloc.h serverassert.h valkey_strtod.h monotonic.h
valkey-benchmark.o: valkey-benchmark.c fmacros.h sds.h ae.h monotonic.h \
  ../deps/libvalkey/include/valkey/valkey.h \
  ../deps/libvalkey/include/valkey/read.h \
  ../deps/libvalkey/include/valkey/visibility.h \
  ../deps/libvalkey/include/valkey/alloc.h adlist.h dict.h mt19937-64.h \
  zmalloc.h crc16_slottable.h ../deps/hdr_histogram/hdr_histogram.h \
  cli_common.h
valkey-check-aof.o: valkey-check-aof.c server.h fmacros.h config.h \
  solarisfixes.h rio.h sds.h connection.h ae.h monotonic.h commands.h \
  allocator_defrag.h dict.h mt19937-64.h hashtable.h kvstore.h adlist.h \
  zmalloc.h anet.h version.h util.h latency.h trace/trace.h \
  trace/trace_aof.h trace/trace_cluster.h trace/trace_server.h \
  trace/trace_db.h trace/trace_rdb.h trace/trace_commands.h sparkline.h \
  quicklist.h expire.h rax.h memory_prefetch.h vset.h entry.h lrulfu.h \
  valkeymodule.h zipmap.h ziplist.h sha1.h endianconv.h crc64.h stream.h \
  listpack.h rdb.h
valkey-check-rdb.o: valkey-check-rdb.c mt19937-64.h server.h fmacros.h \
  config.h solarisfixes.h rio.h sds.h connection.h ae.h monotonic.h \
  commands.h allocator_defrag.h dict.h hashtable.h kvstore.h adlist.h \
  zmalloc.h anet.h version.h util.h latency.h trace/trace.h \
  trace/trace_aof.h trace/trace_cluster.h trace/trace_server.h \
  trace/trace_db.h trace/trace_rdb.h trace/trace_commands.h sparkline.h \
  quicklist.h expire.h rax.h memory_prefetch.h vset.h entry.h lrulfu.h \
  valkeymodule.h zipmap.h ziplist.h sha1.h endianconv.h crc64.h stream.h \
  listpack.h rdb.h module.h ../deps/hdr_histogram/hdr_histogram.h \
  ../deps/fpconv/fpconv_dtoa.h
valkey-cli.o: valkey-cli.c fmacros.h \
  ../deps/libvalkey/include/valkey/valkey.h \
  ../deps/libvalkey/include/valkey/read.h \
  ../deps/libvalkey/include/valkey/visibility.h \
  ../deps/libvalkey/include/valkey/alloc.h sds.h dict.h mt19937-64.h \
  adlist.h zmalloc.h ../deps/linenoise/linenoise.h anet.h ae.h \
  monotonic.h connection.h cli_common.h util.h cli_commands.h commands.h \
  valkey_strtod.h
vector.o: vector.c vector.h serverassert.h zmalloc.h
vset.o: vset.c vset.h hashtable.h fmacros.h rax.h util.h sds.h \
  endianconv.h config.h serverassert.h zmalloc.h server.h solarisfixes.h \
  rio.h connection.h ae.h monotonic.h commands.h allocator_defrag.h \
  dict.h mt19937-64.h kvstore.h adlist.h anet.h version.h latency.h \
  trace/trace.h trace/trace_aof.h trace/trace_cluster.h \
  trace/trace_server.h trace/trace_db.h trace/trace_rdb.h \
  trace/trace_commands.h sparkline.h quicklist.h expire.h \
  memory_prefetch.h entry.h lrulfu.h valkeymodule.h zipmap.h ziplist.h \
  sha1.h crc64.h stream.h listpack.h rdb.h
ziplist.o: ziplist.c zmalloc.h util.h sds.h ziplist.h config.h \
  endianconv.h serverassert.h
zipmap.o: zipmap.c zmalloc.h endianconv.h config.h
zmalloc.o: zmalloc.c fmacros.h config.h solarisfixes.h serverassert.h \
  zmalloc.h
