#define NEXCACHE_GIT_SHA1 "5883fd08"
#define NEXCACHE_GIT_DIRTY "    3418"
#define NEXCACHE_BUILD_ID "MacBookPro.wind3.hub-1775157301"
#include "version.h"
#define NEXCACHE_BUILD_ID_RAW SERVER_NAME NEXCACHE_VERSION NEXCACHE_BUILD_ID NEXCACHE_GIT_DIRTY NEXCACHE_GIT_SHA1
