#define NEXCACHE_GIT_SHA1 "04a6724d"
#define NEXCACHE_GIT_DIRTY "       0"
#define NEXCACHE_BUILD_ID "MacBookPro.wind3.hub-1775053326"
#include "version.h"
#define NEXCACHE_BUILD_ID_RAW SERVER_NAME NEXCACHE_VERSION NEXCACHE_BUILD_ID NEXCACHE_GIT_DIRTY NEXCACHE_GIT_SHA1
