#define NEXCACHE_GIT_SHA1 "00000000"
#define NEXCACHE_GIT_DIRTY "  467971"
#define NEXCACHE_BUILD_ID "MacBookPro.wind3.hub-1773226540"
#include "version.h"
#define NEXCACHE_BUILD_ID_RAW SERVER_NAME NEXCACHE_VERSION NEXCACHE_BUILD_ID NEXCACHE_GIT_DIRTY NEXCACHE_GIT_SHA1
